In [ ]:
!wget https://raw.githubusercontent.com/nachikethmurthy/Source-Code-Dataset-for-Machine-Learning-using-Python/main/Data/store_data.csv

--2023-01-13 02:08:11--  https://raw.githubusercontent.com/nachikethmurthy/Source-Code-Dataset-for-Machine-Learning-using-Python/main/Data/store_data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 302908 (296K) [text/plain]
Saving to: ‘store_data.csv’

store_data.csv      100%[===================>] 295.81K  --.-KB/s    in 0.02s   

2023-01-13 02:08:11 (14.1 MB/s) - ‘store_data.csv’ saved [302908/302908]



In [ ]:
file_data = open('store_data.csv','rt')
store_data = file_data.read()
file_data.close()

In [ ]:
s = 'welcome, to, data, science\nthis,is,class1,\nhello'
r = s.split('\n')
r

['welcome, to, data, science', 'this,is,class1,', 'hello']

In [ ]:
for v in r:
  print(v.split(','))

['welcome', ' to', ' data', ' science']
['this', 'is', 'class1', '']
['hello']


In [ ]:
[v.split(',') for v in r]

[['welcome', ' to', ' data', ' science'],
 ['this', 'is', 'class1', ''],
 ['hello']]

In [ ]:
store_data = store_data.split("\n")
store_data[:3]

['shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil',
 'burgers,meatballs,eggs',
 'chutney']

In [ ]:
store_data = [element.split(',') for element in store_data]
store_data[:3]

[['shrimp',
  'almonds',
  'avocado',
  'vegetables mix',
  'green grapes',
  'whole weat flour',
  'yams',
  'cottage cheese',
  'energy drink',
  'tomato juice',
  'low fat yogurt',
  'green tea',
  'honey',
  'salad',
  'mineral water',
  'salmon',
  'antioxydant juice',
  'frozen smoothie',
  'spinach',
  'olive oil'],
 ['burgers', 'meatballs', 'eggs'],
 ['chutney']]

In [ ]:
from mlxtend.preprocessing import TransactionEncoder
encoder = TransactionEncoder()
encoder.fit(store_data)
transformed_data = encoder.transform(store_data)
transformed_data

array([[False, False,  True, ...,  True, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False],
       [ True, False, False, ..., False, False, False]])

In [ ]:
transformed_data = transformed_data.astype("int")

In [ ]:
encoder.columns_

In [ ]:
import pandas as pd
transformed_df = pd.DataFrame(transformed_data, columns=encoder.columns_)
transformed_df.head()

asparagus  almonds  antioxydant juice  asparagus  avocado  babies food  \
0  0           0        1                  1          0        1            0   
1  0           0        0                  0          0        0            0   
2  0           0        0                  0          0        0            0   
3  0           0        0                  0          0        1            0   
4  0           0        0                  0          0        0            0   

   bacon  barbecue sauce  black tea  ...  turkey  vegetables mix  water spray  \
0      0               0          0  ...       0               1            0   
1      0               0          0  ...       0               0            0   
2      0               0          0  ...       0               0            0   
3      0               0          0  ...       1               0            0   
4      0               0          0  ...       0               0            0   

   white wine  whole weat flour  whole wheat pasta  whole wheat rice  yams  \
0           0                 1                  0                 0     1   
1           0                 0                  0                 0     0   
2           0                 0                  0                 0     0   
3           0                 0                  0                 0     0   
4           0                 0                  0                 1     0   

   yogurt cake  zucchini  
0            0         0  
1            0         0  
2            0         0  
3            0         0  
4            0         0  

[5 rows x 121 columns]

In [ ]:
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
frequent_itemsets = apriori(transformed_df, min_support=0.01, use_colnames=True )
frequent_itemsets

support                                 itemsets
0    0.020395                                (almonds)
1    0.033324                                (avocado)
2    0.010797                         (barbecue sauce)
3    0.014263                              (black tea)
4    0.011464                             (body spray)
..        ...                                      ...
252  0.011064       (ground beef, milk, mineral water)
253  0.017062  (ground beef, spaghetti, mineral water)
254  0.015729         (spaghetti, milk, mineral water)
255  0.010264    (olive oil, spaghetti, mineral water)
256  0.011464     (pancakes, spaghetti, mineral water)

[257 rows x 2 columns]

In [ ]:
frequent_itemsets.sort_values('support', ascending=False)

support                                  itemsets
46   0.238336                           (mineral water)
19   0.179685                                    (eggs)
63   0.174087                               (spaghetti)
24   0.170888                            (french fries)
13   0.163823                               (chocolate)
..        ...                                       ...
255  0.010264     (olive oil, spaghetti, mineral water)
123  0.010131                         (chocolate, soup)
246  0.010131        (ground beef, eggs, mineral water)
249  0.010131  (spaghetti, french fries, mineral water)
175  0.010131       (low fat yogurt, frozen vegetables)

[257 rows x 2 columns]

In [ ]:
len(frequent_itemsets)

257

In [ ]:
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.25)
rules.sort_values('lift',ascending=False)

antecedents      consequents  antecedent support  \
23                     (herb & pepper)    (ground beef)            0.049453   
87          (spaghetti, mineral water)    (ground beef)            0.059717   
86        (ground beef, mineral water)      (spaghetti)            0.040922   
80  (mineral water, frozen vegetables)           (milk)            0.035724   
33                              (soup)           (milk)            0.050520   
..                                 ...              ...                 ...   
30                    (low fat yogurt)  (mineral water)            0.076513   
17                       (fresh bread)  (mineral water)            0.043055   
44                            (turkey)  (mineral water)            0.062517   
15                              (eggs)  (mineral water)            0.179685   
3                            (burgers)  (mineral water)            0.087177   

    consequent support   support  confidence      lift  leverage  conviction  
23            0.098240  0.015996    0.323450  3.292433  0.011137    1.332880  
87            0.098240  0.017062    0.285714  2.908316  0.011195    1.262463  
86            0.174087  0.017062    0.416938  2.395000  0.009938    1.416510  
80            0.129565  0.011064    0.309701  2.390309  0.006435    1.260954  
33            0.129565  0.015196    0.300792  2.321541  0.008650    1.244886  
..                 ...       ...         ...       ...       ...         ...  
30            0.238336  0.023994    0.313589  1.315740  0.005758    1.109632  
17            0.238336  0.013330    0.309598  1.298994  0.003068    1.103217  
44            0.238336  0.019195    0.307036  1.288247  0.004295    1.099139  
15            0.238336  0.050920    0.283383  1.189003  0.008094    1.062860  
3             0.238336  0.024393    0.279817  1.174040  0.003616    1.057597  

[95 rows x 9 columns]

In [ ]:
import numpy as np
x = np.array([1,2,3,4,5]).reshape(5,1) # min=0 & max 1
from sklearn.preprocessing import MinMaxScaler
min = MinMaxScaler()
min.fit_transform(x)

array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

In [ ]:
(x-np.mean(x))/np.std(x)

array([[-1.41421356],
       [-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356]])

In [ ]:
np.mean(x)

3.0

In [ ]:
np.std(x)

1.4142135623730951