In [ ]:
!wget https://raw.githubusercontent.com/nachikethmurthy/Source-Code-Dataset-for-Machine-Learning-using-Python/main/Data/Social_Network_Ads.csv

--2023-01-04 02:37:30--  https://raw.githubusercontent.com/nachikethmurthy/Source-Code-Dataset-for-Machine-Learning-using-Python/main/Data/Social_Network_Ads.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10926 (11K) [text/plain]
Saving to: ‘Social_Network_Ads.csv’

Social_Network_Ads. 100%[===================>]  10.67K  --.-KB/s    in 0s      

2023-01-04 02:37:30 (39.8 MB/s) - ‘Social_Network_Ads.csv’ saved [10926/10926]



In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
# One hot encoding
df.drop(columns='User ID',inplace=True)

In [ ]:
df.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [ ]:
pd.get_dummies(df)

Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0     19            19000          0              0            1
1     35            20000          0              0            1
2     26            43000          0              1            0
3     27            57000          0              1            0
4     19            76000          0              0            1
..   ...              ...        ...            ...          ...
395   46            41000          1              1            0
396   51            23000          1              0            1
397   50            20000          1              1            0
398   36            33000          0              0            1
399   49            36000          1              1            0

[400 rows x 5 columns]

In [ ]:
df = pd.get_dummies(df, columns=['Gender'])
df.head()

Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0   19            19000          0              0            1
1   35            20000          0              0            1
2   26            43000          0              1            0
3   27            57000          0              1            0
4   19            76000          0              0            1

In [ ]:
X = df.drop(columns='Purchased') # inplace=False
y = df['Purchased']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [ ]:
X.head()

Age  EstimatedSalary  Gender_Female  Gender_Male
0   19            19000              0            1
1   35            20000              0            1
2   26            43000              1            0
3   27            57000              1            0
4   19            76000              0            1

In [ ]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [ ]:
log = LogisticRegression()
log.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred = log.predict(X_test)

In [ ]:
y_pred[:5]

array([0, 0, 0, 0, 0])

In [ ]:
y_test[:5]

209    0
280    1
33     0
210    1
93     0
Name: Purchased, dtype: int64

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.65

In [ ]:
df.describe() # Statistical summary of the dataset

Age  EstimatedSalary   Purchased  Gender_Female  Gender_Male
count  400.000000       400.000000  400.000000     400.000000   400.000000
mean    37.655000     69742.500000    0.357500       0.510000     0.490000
std     10.482877     34096.960282    0.479864       0.500526     0.500526
min     18.000000     15000.000000    0.000000       0.000000     0.000000
25%     29.750000     43000.000000    0.000000       0.000000     0.000000
50%     37.000000     70000.000000    0.000000       1.000000     0.000000
75%     46.000000     88000.000000    1.000000       1.000000     1.000000
max     60.000000    150000.000000    1.000000       1.000000     1.000000

In [ ]:
# Apply the scaling
# StandardScaler --> to scale the data with mean as 0 and standard deviation as 1
# Usage of binary values has little effect on the accuracy of Logistic Regression model
df_data = df[['Age','EstimatedSalary']]

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(df_data)

StandardScaler()

In [ ]:
(ss.mean_)

array([3.76550e+01, 6.97425e+04])

In [ ]:
ss.var_ # variance

array([1.09615975e+02, 1.15969619e+09])

In [ ]:
df_transform = ss.transform(df_data)

In [ ]:
pd.DataFrame(df_transform).describe()

0             1
count  4.000000e+02  4.000000e+02
mean  -7.105427e-17 -1.776357e-17
std    1.001252e+00  1.001252e+00
min   -1.877311e+00 -1.607506e+00
25%   -7.550313e-01 -7.852897e-01
50%   -6.256110e-02  7.561451e-03
75%    7.970571e-01  5.361289e-01
max    2.134241e+00  2.356750e+00

In [ ]:
X_new = df_transform

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_new,y,test_size=0.2, random_state=42)

log = LogisticRegression()
log.fit(X_train,y_train)

y_pred = log.predict(X_test)
accuracy_score(y_test,y_pred)

0.8625

In [ ]:
df.head()

Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0   19            19000          0              0            1
1   35            20000          0              0            1
2   26            43000          0              1            0
3   27            57000          0              1            0
4   19            76000          0              0            1

In [ ]:
data = pd.read_csv('/content/Social_Network_Ads.csv')
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
data['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
pd.get_dummies(data).head()

User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0  15624510   19            19000          0              0            1
1  15810944   35            20000          0              0            1
2  15668575   26            43000          0              1            0
3  15603246   27            57000          0              1            0
4  15804002   19            76000          0              0            1

In [ ]:
data["New Column"] = data["Gender"]

In [ ]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased New Column
0  15624510    Male   19            19000          0       Male
1  15810944    Male   35            20000          0       Male
2  15668575  Female   26            43000          0     Female
3  15603246  Female   27            57000          0     Female
4  15804002    Male   19            76000          0       Male

In [ ]:
pd.get_dummies(data)

User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male  \
0    15624510   19            19000          0              0            1   
1    15810944   35            20000          0              0            1   
2    15668575   26            43000          0              1            0   
3    15603246   27            57000          0              1            0   
4    15804002   19            76000          0              0            1   
..        ...  ...              ...        ...            ...          ...   
395  15691863   46            41000          1              1            0   
396  15706071   51            23000          1              0            1   
397  15654296   50            20000          1              1            0   
398  15755018   36            33000          0              0            1   
399  15594041   49            36000          1              1            0   

     New Column_Female  New Column_Male  
0                    0                1  
1                    0                1  
2                    1                0  
3                    1                0  
4                    0                1  
..                 ...              ...  
395                  1                0  
396                  0                1  
397                  1                0  
398                  0                1  
399                  1                0  

[400 rows x 8 columns]

In [ ]:
cancer = pd.read_csv('data.csv')

In [ ]:
cancer.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
# Apply standard scaler on features and see if its improving accuracy