In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv("BostonHousing.csv")
data.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [ ]:
# Data Wrangling
x= data.iloc[:,0:13]
y= data["medv"]
x,y

(        crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
 0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
 1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
 2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
 3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
 4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
 ..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
 501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
 502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
 503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
 504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
 505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   
 
      ptratio       b  lstat  
 0       15.3  396.90   4.98  
 1       17.8  396.90   9.14  
 2       17.8  39

In [ ]:
# Train Algorithm
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=5)

In [ ]:
x_train.shape

(339, 13)

In [ ]:
x_test.shape

(167, 13)

In [ ]:
data.shape

(506, 14)

In [ ]:
# Fitting model to train and test
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
model = lm.fit(x_train,y_train)

In [ ]:
lm.coef_ #slope of the line

array([-1.56381297e-01,  3.85490972e-02, -2.50629921e-02,  7.86439684e-01,
       -1.29469121e+01,  4.00268857e+00, -1.16023395e-02, -1.36828811e+00,
        3.41756915e-01, -1.35148823e-02, -9.88866034e-01,  1.20588215e-02,
       -4.72644280e-01])

In [ ]:
lm.intercept_ #interceptor 

32.858932634086024

In [ ]:
# y = 32.85 + -1.56*X

In [ ]:
# Evaluation Model
# r2-score
#values ranginf from 0 to 1

In [ ]:
from sklearn.metrics import r2_score

# r2 expects  predicate output and lable output (given data)

In [ ]:
x_train[0:5]

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
435  11.16040   0.0  18.10     0  0.740  6.629  94.6  2.1247   24  666   
88    0.05660   0.0   3.41     0  0.489  7.007  86.3  3.4217    2  270   
365   4.55587   0.0  18.10     0  0.718  3.561  87.9  1.6132   24  666   
242   0.10290  30.0   4.93     0  0.428  6.358  52.9  7.0355    6  300   
461   3.69311   0.0  18.10     0  0.713  6.376  88.4  2.5671   24  666   

     ptratio       b  lstat  
435     20.2  109.85  23.27  
88      17.8  396.90   5.50  
365     20.2  354.70   7.12  
242     16.6  372.75  11.22  
461     20.2  391.43  14.65

In [ ]:
y_train.head()

435    13.4
88     23.6
365    27.5
242    22.2
461    17.7
Name: medv, dtype: float64

In [ ]:
y_pred = lm.predict(x_train)
y_pred[:5]

array([13.16072876, 30.41654502, 13.56155988, 24.31597165, 20.60168017])

In [ ]:
# Evaulation 
r2_score(y_train,y_pred)

0.7551332741779998

In [ ]:
# Least Mean Square Error
from sklearn.metrics  import mean_squared_error

mean_squared_error(y_train,y_pred)

19.546758473534666

In [ ]:
# Mean absolute Square Error
from sklearn.metrics  import mean_absolute_error

mean_absolute_error(y_train,y_pred)

3.121946795254281

In [ ]:
# Root Mean Square Error
from sklearn.metrics  import mean_squared_error

mean_squared_error(y_train,y_pred,squared=False)

4.421171617742821

In [ ]:
# Testing
pred_y = lm.predict(x_test)
pred_y

array([37.46723562, 31.39154701, 27.1201962 ,  6.46843347, 33.62966737,
        5.67067989, 27.03946671, 29.92704748, 26.35661334, 22.45246021,
       32.20504441, 21.78641653, 23.41138441, 33.60894362, 28.28619511,
       15.13859055,  0.30087325, 18.71850376, 14.4706712 , 11.10823598,
        2.69494197, 19.21693734, 38.41159345, 24.36936442, 31.61493439,
       11.42210397, 24.92862188, 23.31178043, 22.7764079 , 20.65081211,
       16.035198  ,  7.07978633, 17.65509209, 22.81470561, 29.21943405,
       18.61354566, 28.37701843,  8.80516873, 41.65140459, 34.02910176,
       20.1868926 ,  3.95600857, 29.69124564, 12.18081256, 27.19403498,
       30.63699231, -6.24952457, 19.9462404 , 21.55123979, 13.36478173,
       20.39068171, 19.87353324, 23.57656877, 13.40141285, 17.66457201,
       24.77424747, 35.31476509, 15.48318159, 28.50764575, 21.72575404,
       20.58142839, 26.08460856, 14.51816968, 32.37494056, 20.80917392,
       12.18932524, 19.45551285, 25.23390429, 21.77302317, 21.30